### ISSUE TITLE
Increase Tolerance for Failures

### ISSUE THREAD

**Issue by hp0404** [jamesoff/simplemonitor#1102]
Hi there,
I'm having trouble figuring out how to increase the tolerance for failures. Currently, the monitor status changes as soon as there is a single failure (here's are telegram alerter messages and I'm also logging results into sqlite db)
```
Failed at: 2022-12-24 20:59:25+00:00 (down 0+00:00:00)
Virtual failure count: 1
Additional info: Request timeout for ICMP packet. (Timeout=5s)

Recovered at: 2022-12-24 21:00:25+00:00
Additional info: Ping time 32.267ms
```

but I would like it to only change if there are two consecutive failures (it's always 1 minute at max, so I always see 1 1 1 0 1 1, etc., and so I'd like to treat it as 0 only if there are two consecutive 0: 1 1 1 0 0 1, all good otherwise (1 1 1 1 1 1)). 
I already tried increasing tolerance in monitor.ini file, but it didn't help. 
```
[monitor]
interval=60
tolerance=3
```
Could you please help me understand how to make this change?

Thank you in advance for any guidance you can provide.

I currently fix it (in the database, not with the alerter, sadly) with the following SQL statement:
```SQL
WITH t AS (
    SELECT 
        result_id,
        monitor_result,
        SUM(CASE WHEN monitor_result != previous_status THEN 1 ELSE 0 END) OVER(ORDER BY result_id) + 1 AS session_id
    FROM (
        SELECT 
            *,
            LAG(monitor_result, 1) OVER(ORDER BY result_id) AS previous_status
        FROM results
    ) s
),
false_session AS (
    SELECT session_id
    FROM t
    WHERE monitor_result = 0
    GROUP BY session_id
    HAVING COUNT(*) = 1
)
UPDATE results
SET monitor_result = 1
WHERE result_id IN (
    SELECT result_id FROM t WHERE session_id IN (
        SELECT session_id FROM false_session
    )
);
```

**Comment by jamesoff** [comment]
Hey there :)

You need to put `tolerance=3` on your actual monitor's configuration, not in the `[monitor]` section.

That is, in `monitors.ini` you want something like this:

```
[my-ping-monitor]
type=ping
host=some.host
tolerance=3
```

That should do what you want.

If you have many monitors you want this to apply to, you can add a `defaults` section to `monitors.ini` (at the top):

```
[defaults]
tolerance=3
```

Then all monitors will inherit this value. You can override it on individual monitors as required.

Off the top of my head, I don't recall if Loggers respect `tolerance`; they may still report that the monitor is in a failed state (because the test failed). Let me know if that's something you'd like to be able to distinguish, I'm sure I can add a column to the database schema for it.

**Comment by hp0404** [comment]
Thanks! Your suggestion fixed my problem. 
As for the schema, I use simplemonitor to track my network outages - so I aggregate data into the table that looks like this:
```
status|start|end|duration
Online|2022-12-26 12:21:22|2022-12-26 14:06:33|1h 45m 11s
Offline|2022-12-26 09:20:02|2022-12-26 12:20:21|3h 0m 19s
Online|2022-12-24 10:38:32|2022-12-26 09:18:57|46h 40m 25s
Offline|2022-12-24 10:36:27|2022-12-24 10:37:32|0h 1m 5s
Online|2022-12-24 10:33:21|2022-12-24 10:35:22|0h 2m 1s
```
Then once the status changes, I send an alert. 

I don't know if additional columns are needed. In my case, the query is pretty straightforward.

**Comment by jamesoff** [comment]
Awesome, glad you were able to make it do what you needed :)
