### ISSUE TITLE
How to get the monitors and monitoring results?

### ISSUE THREAD

**Issue by wsw70** [jamesoff/simplemonitor#236]
I <del>started to write</del> wrote an MQTT logger (EDIT: the alpha version works, I need to add some configuring before raising a PR, and also learn how to write tests...) but have some problems understanding the architecture (I am an amateur developer)

1. How to get the list of monitors (the targets which are being monitored) in the `_init_` of the new `Logger` class? I will need at that point to register topics with MQTT, one topic per monitor. 

1. <del>My understanding is that `save_result2()` is fired at each monitoring cycle, once for each monitor. Is that correct?</del> Confirmed.

**Comment by wsw70** [comment]
> I  will need at that point to register topics with MQTT, one topic per monitor.

I found a workaround by keeping a list with the monitors, updated once and then checked against - in `save_result2()`.

If there is a way to know the monitors in `_init_` then registering there would be more elegant but if not, this is not a problem as the workaround is OK too.

**Comment by jamesoff** [comment]
Sorry for not replying sooner, I was away.

Yes, the idea is that instead of Loggers getting access to the Monitors in the main program, there's a system whereby they are given all the monitor results in a batch and then told the batch is complete, which is when they should trigger whatever output contains all the results.

Loggers which have `supports_batch` set to `False` should immediately act on the call to `save_result2()` - e.g. FileLogger writes a line to its output file. (It could also support batched mode and buffer all the lines before writing them out in one go, but that isn't the way the code evolved; batch mode was an addition when I realised some loggers needed to know all the results before they started writing output.)

There's a couple of potential concerns with telling a Logger about all the Monitors which are loaded (during init): first, when the Logger is created (while the config is loaded), we don't know what remote monitors we might get sent from another instance; and second, I'd rather not have Loggers hold a reference to each Monitor (which feels "wrong", in a programming sense).

The latter is a problem which could be address with `weakref`, although I've not used it before. The former is a harder problem though. I'm not very familiar with MQTT, but are you able to register topics on your endpoint ad hoc (i.e., when your `save_result2()` is called, you can consult a list in your object to see if you've already registered that one, and if not register it and add to the list). That way the first time the loop runs and your logger processes its batch, every local monitor will be registered on your endpoint. If any come in over the network after that, they'll be registered on the next batch process.

Hope that makes sense, and if it's not what you need let me know and we can come at it from a different angle :)

And thanks for the contributions!

**Comment by jamesoff** [comment]
Oh, you said about keeping the list updated as you receive the calls to `save_result2()`, I missed that somehow! If that does work for you it would be my preferred solution :)

**Comment by wsw70** [comment]
Yes, it works perfectly. I have the code working for a few days now and need to 

- improve the comments (they are not bas as of now but I prefer to be explicit)
- add a few configuration entries especially around Home Assistant: that way the logger will work as a generic MQTT client (default, with a complete JSON payload) and also make extra MQTT calls specific to Home Assistant if enabled.

A heads-up of the final result on Home Assistant (the dots are `simplemonitor` monitors)

![image](https://user-images.githubusercontent.com/1345886/52591734-eff55f80-2e44-11e9-9672-0fe300a6e637.png)

**Comment by wsw70** [comment]
https://github.com/jamesoff/simplemonitor/pull/244
