### ISSUE TITLE
Elapsed time in log file

### ISSUE THREAD

**Issue by hattesen** [jamesoff/simplemonitor#33]
When performing internet-based requests (HTTP, Ping, DNS), it can be important not only to be able to detect failures, but also be able to determine the duration (milliseconds) of a request.

As a minimum, it would be nice to be able to append the duration onto each log line, e.g.

**monitor.log:**
```
1469763249 dr-http: ok (150ms)
1469763249 dr-ping: ok (42ms)
1469763260 dr-http: ok (142ms)
...
```

An additional option would be to be able to set a maximum acceptable duration on the completion of a monitor request, and have a failure reported if this duration is exceeded.

**Comment by jamesoff** [comment]
I'm going to create a separate issue for the maximum duration for a check as that's going to be more involved than just counting the elapsed time :)

**Comment by hattesen** [comment]
Sounds like a good plan. Ideally, requests should be made asynchronous so they can be set to time out when the max duration is reached rather than having to wait until the request itself times out. Async/concurrent coding is not easy, I know, but libraries may be available to ease the task

**Comment by jamesoff** [comment]
Yeah, I was planning on doing the version where the request is killed if it goes over the duration rather than waiting and then failing because it took too long - and that's exactly why I'm pushing it to look at another time ;)

Looks like the `signal` module can do SIGALRM so hopefully I can cobble something together with that!
