### ISSUE TITLE
returned non-zero exit status 1

### ISSUE THREAD

**Issue by milezzz** [jamesoff/simplemonitor#350]
This is driving me batty...wish you had more examples of monitor(s).ini somewhere.

```
ERROR (simplemonitor) monitor failed: dummyhost-ping (Command '['ping', '-c1', '-W5', '12.12.12.12']' returned non-zero exit status 1)
```

My monitors.ini:

```
[dummyhost-ping]
type=host
host=12.12.12.12 #for testing
tolerance=2
```

monitor.ini

```
[monitor]
interval=1 #for testing

[check-8kun--http]
type=http
url=https://mydomain.com
allowed_codes=200

[reporting]
loggers=logfile
alerters=email

[logfile]
type=logfile
filename=monitor.log
only_failures=1

[email]
type=email
host=smtp.mailgun.com
from=mg@mydomain.com
to=someone@domain.com
username=postmaster@mydomain.com
password=somepassword
ssl=starttls
```

Any idea what is causing the error?

**Comment by jamesoff** [comment]
`man ping` on my Linux (Raspbian) host says,

> If ping does not receive any reply packets at all it will exit with code 1.

So your ping monitor is going into the error state because it's not getting any response from 12.12.12.12. (I'll admit the message there isn't super helpful, but unfortunately `ping` behaves slightly differently on different OSes except for always exiting 0 on success. I'm looking at using a Python-native ping module (see #102) but it does mean SimpleMonitor will need to run as root.

**Comment by milezzz** [comment]
Hey thanks for the response James! How would you do something simple like this:  fail/succeed when a ping actually works/doesn't work ? 

Also maybe you can diagnose my DNS check which doesn't seem to fail when it should:

```
[dns]
record=somedomain.com
record_type=A
desired_val=8.208.15.90
```

In this case dig returns no records at all but the monitor does not fail. Is my syntax ok?
