### ISSUE TITLE
configparser.NoOptionError: No option 'type' in section: 'monitor'

### ISSUE THREAD

**Issue by alinuxexpert** [jamesoff/simplemonitor#633]
I created a monitor.ini with the collowing monitor section:

[monitor]
interval=60

When I run simplemonitor (using --config=monitor.ini), I get the error message

configparser.NoOptionError: No option 'type' in section: 'monitor'

Seems to me like simplemonitor attempts to interpret the monitor section as one of the monitors. However, I have a separate monitors.ini which does not contain a monitor section.

simplemonitor 1.10.0

**Comment by jamesoff** [comment]
Hi!

Do you have a `monitors.ini` too? Due to poor design choices some years ago, the main and logging/alerting config goes in `monitor.ini` and the monitors all go in `monitors.ini`. (You can override the filename for the second by setting `monitors=some-filename.ini` in the same section as `interval` in `monitor.ini`.)

Would you mind sharing your config files? Happy for them to be abridged if there's things in there you'd rather not share.

Thanks :)

**Comment by alinuxexpert** [comment]
I cannot reproduce this issue, thus, I'm closing it.

**Comment by jamesoff** [comment]
Thanks for the update. If you encounter the problem again, please let me know :)
