### ISSUE TITLE
{virtual_fail_count} is always 0

### ISSUE THREAD

**Issue by azlux** [jamesoff/simplemonitor#69]
Hi,
I've use simplemonitor since few week, and I saw that into the `fail_command` and `success_command` (into the file monitors.ini) keep the variable `{virtual_fail_count}` to zero.
Do you have an idea how to debug that ?
I'm on the branch feature/python3. (But it was the same on the master branch)

**Comment by jamesoff** [comment]
You mean if you put `{virtual_fail_count}` in your `fail_command` (or success) it always comes out as zero?

I'd probably debug it with some `print` statements ;) do you have a small configuration which shows the problem?

**Comment by azlux** [comment]
Yes.
[Here my monitor.ini / monitors.ini and debug](https://azlux.fr/bin/?4d0b8cdd6bfffbc7#lBQNT43hkoyByKbvAnbLcJ1yl+i6FmrR7Ze3cEZa57s=)

**Comment by jamesoff** [comment]
Thanks! I should be able to take a look later today :)

**Comment by jamesoff** [comment]
@azlux I see the problem, virtual_fail_count is zero when the success handler runs because by then the monitor has succeeded and reset the failure count etc. Luckily, it remembers what the last error count was, so I've added that to the things you can use. If you (pull the latest version and) swap `{virtual_fail_count}` for `{last_virtual_fail_count}` in your `success_command` it should do what you want.
