### ISSUE TITLE
Sudo privileges & Cron jobs

### ISSUE THREAD

**Issue by Rustymage** [jamesoff/simplemonitor#84]
Hi,

I'm reasonably new to the pi and coding, I dabble a little and can make other peoples code work (they've done the hard work). I can also try to diagnose by using commands and understanding the output. I'm also happy to look through code and try to find whats going on.

I spent the whole afternoon trying to get Simplemonitor to run on reboot and I'm beyond my knowledge level now so please help!

I have two issues:

First problem:

I’ve setup the system to run manually if I use the command **sudo python monitor.py** but when running without root privileges I get this:

```
_SimpleMonitor v1.7
--> Loading main config from monitor.ini
--> Loading monitor config from monitors.ini
No monitors loaded :(_
```

It runs happily with the sudo command.

Why is this the case, have I got permission issues I’ve not seen in some of the files?

Second problem

I've asked the python script to run on reboot under either the pi user or root user cron jobs, I've also requested a log be kept but I keep getting told this:

```
_SimpleMonitor v1.7
--> Loading main config from monitor.ini
--> Configuration file "monitor.ini" does not exist!_
```

Here is the code used:

`_@reboot sleep 60 && python /home/pi/jamesoff-simplemonitor-abbfb03/monitor.py -d > /var/log/cronlog 2>&1_`

I have also tried running a bach script from cron, however that also gives me errors. I can see the cron request getting run in syslog:

```
_Apr 14 21:11:53 raspberrypi cron[376]: (CRON) INFO (Running @reboot jobs)
Apr 14 21:11:53 raspberrypi CRON[417]: (root) CMD (sleep 60 && python /home/pi/jamesoff-simplemonitor-abbfb03/monitor.py -d > /var/log/cronlog 2>&1)_
```

What have I done wrong? Can I provide any more data to help diagnose?

Thanks in advance

Anthony

**Comment by jamesoff** [comment]
Hi!

For your first problem, it's possible that, as you suspect, you have files which the non-root user can't read. What does `ls -l` show in the directory where simplemonitor and your config files are? Note that simplemonitor may actually need to run as root for some of the checks to work (like if you're checking if a service is running... non-root may not be able to do that).

For your second problem, I think the problem is that when cron runs the script, the working directory is not right, so the code can't find the file. You could try adding `cd /home/pi/jamesoff-simplemonitor-abbfb03` as a command between the `sleep` and the `python`

(i.e. `@reboot sleep 60 && cd /home/pi/jamesoff-simplemonitor-abbfb03  && python /home/pi/jamesoff-simplemonitor-abbfb03/monitor.py -d > /var/log/cronlog 2>&1`)

However, a better approach is to run simplemonitor under some service manager. Assuming your pi is on a current Raspbian/Debian then you'll have `systemd` for that. Currently I'm not including a systemd config file for simplemonitor in the distribution although I've been meaning to. However, here's a minimally-tested config file. 

* Put it in `/etc/systemd/system` as `simplemonitor.service`. Edit it to set the correct path and any options.
* As root, `systemctl enable simplemonitor`. It should tell you `Created symlink from /etc/systemd/system/multiuser.target.wants/simplemonitor.service to /etc/systemd/system/simplemonitor.service.` or similar.
* You can then `systemctl start simplemonitor` and `systemctl stop simplemonitor` to control the service. `systemctl status simplemonitor` will show you if it's running or not, and the most recent log lines.

It should also start on boot, but I'm not in a position to restart my pi to double-check ;)

Let me know if that works for you and I'll include it in the distribution if so!

**Comment by Rustymage** [comment]
Thanks, I'll have a crack at it tomorrow night and get back to you!

**Comment by Rustymage** [comment]
drwxr-xr-x 2 pi   pi    4096 Apr 14 19:58 Alerters
drwxr-xr-x 2 pi   pi    4096 Mar 12 23:21 build
-rw-r--r-- 1 pi   pi    2519 Mar 12 23:21 CHANGELOG
drwxr-xr-x 2 pi   pi    4096 Mar 12 23:21 docker
-rw-r--r-- 1 pi   pi    3044 Mar 12 23:21 envconfig.py
-rw-r--r-- 1 root root  3322 Apr 14 19:58 envconfig.pyc
drwxr-xr-x 2 pi   pi    4096 Mar 12 23:21 html
-rw-r--r-- 1 pi   pi    1484 Mar 12 23:21 LICENCE
drwxr-xr-x 2 pi   pi    4096 Apr 14 19:58 Loggers
-r--r--r-- 1  777 root   414 Apr 15 10:47 monitor.ini
-rw-r--r-- 1 root root  1074 Apr 15 10:39 monitor.log
-rw-rw-rw- 1  777 root 15287 Mar 12 23:21 monitor.py
drwxr-xr-x 2 pi   pi    4096 Apr 14 19:58 Monitors
-rw------- 1 root root   161 Apr 14 21:24 monitors.ini
-rw-r--r-- 1 pi   pi      49 Mar 12 23:21 monitors.ini-dist
-rw-r--r-- 1 pi   pi      49 Mar 12 23:21 monitors.ini-sample
-rw-r--r-- 1 pi   pi     399 Mar 12 23:21 monitor.sql
-rw------- 1 root root  1150 Apr 18 20:54 nohup.out
-rw-r--r-- 1 pi   pi     658 Mar 12 23:21 README.md
-rwx--x--x 1  777 root   106 Apr 14 20:23 rebootscript.sh
-rw-r--r-- 1 pi   pi      40 Mar 12 23:21 requirements.txt
drwxr-xr-x 4 pi   pi    4096 Mar 12 23:21 scripts
-rw-r--r-- 1 pi   pi    9422 Mar 12 23:21 simplemonitor.py
-rw-r--r-- 1 root root  8924 Apr 14 19:58 simplemonitor.pyc
drwxr-xr-x 4 pi   pi    4096 Mar 12 23:21 tests

**Comment by Rustymage** [comment]
Running **@reboot sleep 60 && python /home/pi/jamesoff-simplemonitor-abbfb03/monitor.py -d | tee -a /var/log/cronlog** works!

**Comment by jamesoff** [comment]
For the first issue, the problem is caused by mainly this:

```
-rw------- 1 root root 161 Apr 14 21:24 monitors.ini
```

Your monitors.ini is owned by root and is not world-readable, so when you run the script as the non-root user, it can't access the file. You can either: run simplemonitor as root (which you may need if you want to check if services are running), or fix ownership of that file: `chown pi:pi monitors.ini` so you can run it as non-root. There are other files in that listing which are owned by root too which may cause odd behaviour, but this is the root (haha) cause of the initial problem you were having :)

**Comment by jamesoff** [comment]
For the systemd issue, we can look at the docs and see the likely cause of the 203 exit code: https://www.freedesktop.org/software/systemd/man/systemd.exec.html (scroll to the table at the end). So we need to check all the paths in your config file.
* `WorkingDirectory` needs to be where you put SimeleMonitor; systemd will change to this directory before trying to start the script (and that's what we need), so yours should be set to `/home/pi/jamesoff-simplemonitor-abbfb03` by the looks of it.
* `ExecStart` needs to be the path to your `python` executable followed by `monitor.py`, because we want Python to run that script (and `monitor.py` is not directly executable itself). You can check where python is by running: `which python`. On my Pi, it's `/usr/bin/python` so hopefully yours is the same. Set the ExecStart parameter to that path and add monitor.py, like in my Gist link.
* Don't forget to set the `User` parameter to the user you want to run it as; probably root.

If you want to test it, then you could, as the user specified in your file, run:
```sh
cd THE_WORKING_DIRECTORY_VALUE
THE_EXEC_START_LINE
```

So with my example config file which has:
```
ExecStart=/usr/bin/python monitor.py
WorkingDirectory=/home/james/src/simplemonitor
User=james
```

I can test it like so:
```
james@pi3 ~ % cd /home/james/src/simplemonitor
james@pi3 ~src/simplemonitor % /usr/bin/python monitor.py
SimpleMonitor v1.7
--> Loading main config from monitor.ini
--> Loading monitor config from monitors.ini
Adding host monitor hue-bridge: checking host 192.168.3.18 is pingable
--> Loaded 1 monitors.

Adding logfile logger logfile
()
--> Starting... (loop runs every 60s) Hit ^C to stop
...
```

Once you've changed the `simplemonitor.service` file on disk, tell systemd to reload it: `systemctl daemon-reload`

And try starting the service: `systemctl start simplemonitor`

Fingers crossed! :)

**Comment by Rustymage** [comment]
`root@raspberrypi:/home/pi/jamesoff-simplemonitor-abbfb03# systemctl status simplemonitor
● simplemonitor.service
   Loaded: loaded (/etc/systemd/system/simplemonitor.service; enabled)
   Active: active (running) since Sun 2018-04-22 09:54:04 BST; 9s ago
 Main PID: 11702 (python)
   CGroup: /system.slice/simplemonitor.service
           └─11702 /usr/bin/python monitor.py

Apr 22 09:54:04 raspberrypi systemd[1]: Started simplemonitor.service.`

**Comment by jamesoff** [comment]
Well that's something. I'm not hugely experienced with systemd, but this:
https://superuser.com/questions/955922/enabled-systemd-unit-does-not-start-at-boot
suggests maybe you need to re-enable it after editing it – even though it says enabled now (that matches the output in the question linked too).

**Comment by jamesoff** [comment]
Oh also it might need to be `multi-user.target` at the end. I typed that from memory which is why there's no hyphen in my gist.

**Comment by Rustymage** [comment]
It works! I followed the `multi-user.target` comment and re-enabled, worked first time.

```
pi@raspberrypi:~ $ sudo systemctl status simplemonitor
● simplemonitor.service
   Loaded: loaded (/etc/systemd/system/simplemonitor.service; enabled)
   Active: active (running) since Thu 2018-05-03 23:03:33 BST; 1min 24s ago
 Main PID: 374 (python)
   CGroup: /system.slice/simplemonitor.service
           └─374 /usr/bin/python monitor.py
```

Thanks for all your support.

**Comment by jamesoff** [comment]
Glad we got it sorted!
